# Generated by Django 5.0.2 on 2024-02-14 00:58

from django.db import migrations


def generate_thirty_artists(apps, schema_editor):
    Artist = apps.get_model("music_app", "Artist")

    some_well_known_artist_names = [
        "The Beatles",
        "The Rolling Stones",
        "The Who",
        "The Kinks",
        "The Animals",
        "The Yardbirds",
        "The Byrds",
        "The Hollies",
        "The Mars Volta",
        "The Strokes",
        "The White Stripes",
        "The Black Keys",
        "The Raconteurs",
        "The Dead Weather",
        "The Last Shadow Puppets",
        "Nirvana",
        "Pearl Jam",
        "Soundgarden",
        "Alice in Chains",
        "Mudhoney",
        "Badly Drawn Boy",
        "The Libertines",
        "Björk",
        "Sigur Rós",
        "Broadcast",
        "The Knife",
        "The Cardigans",
        "The Hives",
        "The Vines",
        "The Kills",
    ]

    for name in some_well_known_artist_names:
        Artist.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0002_album_release_date"),
    ]

    operations = [
        migrations.RunPython(generate_thirty_artists),
    ]
